# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'grades',
                'verbose_name': 'grade',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name')),
            ],
            options={
                'verbose_name_plural': 'groups',
                'verbose_name': 'group',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lioncore.Grade', verbose_name='grade')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lioncore.Group', verbose_name='group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pupils',
                'verbose_name': 'pupil',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplomas', models.TextField(verbose_name='diplomas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'teachers',
                'verbose_name': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'wardens',
                'verbose_name': 'warden',
            },
        ),
        migrations.AddField(
            model_name='pupil',
            name='wardens',
            field=models.ManyToManyField(to='lioncore.Warden', verbose_name='wardens'),
        ),
        migrations.AddField(
            model_name='group',
            name='class_teacher',
            field=models.ManyToManyField(to='lioncore.Teacher', verbose_name='class teacher'),
        ),
    ]
