# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lioncore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('groups', models.ManyToManyField(blank=True, to='lioncore.Group', verbose_name='groups')),
                ('teachers', models.ManyToManyField(blank=True, to='lioncore.Teacher', verbose_name='teachers')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
