# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lioncore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'pupil', 'verbose_name_plural': 'pupils'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterModelOptions(
            name='warden',
            options={'verbose_name': 'warden', 'verbose_name_plural': 'wardens'},
        ),
    ]
